# Generated by Django 5.2.15 on 2026-07-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='other', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
