# Generated by Django 5.2.15 on 2026-07-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldi_app', '0002_alter_budgetcategory_category_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='monthly_target',
            new_name='monthly_limit',
        ),
    ]
